"""OptiCrop – Flask crop recommendation application."""

import io
from pathlib import Path

from flask import Flask, jsonify, redirect, render_template, request, send_file, url_for

from ml.location_weather import fetch_live_weather, search_locations
from ml.predictor import get_metrics, predict, validate_inputs
from ml.soil_upload import parse_upload

BASE_DIR = Path(__file__).resolve().parent
MODEL_PATH = BASE_DIR / "models" / "random_forest.pkl"


def _build_prediction_pdf(result: dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.pdfgen import canvas
    except ImportError as exc:
        raise RuntimeError("PDF export dependency missing. Install reportlab.") from exc

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    left = 42
    y = height - 40

    def ensure_space(needed: int):
        nonlocal y
        if y < needed:
            pdf.showPage()
            y = height - 40

    def draw_header():
        nonlocal y
        pdf.setFillColor(colors.HexColor("#14532d"))
        pdf.rect(0, height - 110, width, 110, fill=1, stroke=0)
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 24)
        pdf.drawString(left, height - 64, "OptiCrop")
        pdf.setFont("Helvetica", 12)
        pdf.drawString(left, height - 86, "Crop Recommendations Report")
        pdf.setFont("Helvetica", 9)
        pdf.drawRightString(width - left, height - 86, "Generated by OptiCrop ML Engine")
        y = height - 130

    def section_title(text: str):
        nonlocal y
        ensure_space(95)
        pdf.setFillColor(colors.HexColor("#ecfdf5"))
        pdf.setStrokeColor(colors.HexColor("#86efac"))
        pdf.roundRect(left - 4, y - 17, width - (left * 2) + 8, 22, 6, fill=1, stroke=1)
        pdf.setFillColor(colors.HexColor("#14532d"))
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(left + 4, y - 3, text)
        y -= 26

    def body_line(text: str, size: int = 10, bold: bool = False, gap: int = 14):
        nonlocal y
        ensure_space(80)
        pdf.setFillColor(colors.HexColor("#0f172a"))
        pdf.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        pdf.drawString(left, y, text)
        y -= gap

    inputs = result.get("inputs", {})
    location = result.get("location", {})
    location_label = location.get("label") or ", ".join(
        str(v) for v in [location.get("village"), location.get("city"), location.get("district"), location.get("state")] if v
    )
    draw_header()

    section_title("Primary Recommendation")
    body_line(f"Top Crop: {result.get('crop', 'N/A')}", bold=True)
    body_line(f"Prediction Confidence: {result.get('confidence', 'N/A')}%")
    body_line(f"Recommended Season: {result.get('recommended_season', result.get('season', 'N/A'))}")
    body_line(f"Location: {location_label or 'N/A'}")

    y -= 4
    section_title("Analyzed Soil and Weather Inputs")
    body_line(
        f"N: {inputs.get('N', 'N/A')}   P: {inputs.get('P', 'N/A')}   K: {inputs.get('K', 'N/A')}   pH: {inputs.get('ph', 'N/A')}"
    )
    body_line(
        f"Temperature: {inputs.get('temperature', 'N/A')} C   Humidity: {inputs.get('humidity', 'N/A')}%   Rainfall: {inputs.get('rainfall', 'N/A')} mm"
    )

    y -= 4
    section_title("Top Suitable Crops")
    for idx, crop in enumerate((result.get("suitable_crops") or [])[:8], start=1):
        body_line(
            f"{idx}. {crop.get('crop', 'N/A')} | Overall: {crop.get('combined_score', crop.get('confidence', 'N/A'))}% | "
            f"ML: {crop.get('confidence', 'N/A')}% | Season Fit: {crop.get('season_fit', 'N/A')}%",
            size=9,
            gap=13,
        )

    y -= 4
    section_title("Soil and Climate Analysis")
    for a in result.get("analysis", [])[:10]:
        body_line(f"- {a.get('label', 'Parameter')}: {a.get('status', 'N/A')} ({a.get('pct', 'N/A')}% fit)", size=9)

    y -= 10
    ensure_space(65)
    pdf.setStrokeColor(colors.HexColor("#cbd5e1"))
    pdf.line(left, y, width - left, y)
    y -= 14
    pdf.setFillColor(colors.HexColor("#334155"))
    pdf.setFont("Helvetica", 9)
    pdf.drawString(left, y, f"Model: {result.get('model_name', 'Random Forest')} | Accuracy: {result.get('model_accuracy', 'N/A')}%")
    pdf.drawRightString(width - left, y, "Generated by OptiCrop")

    pdf.save()
    buffer.seek(0)
    return buffer.read()

DOC_GROUPS = [
    {
        "id": "brainstorming",
        "title": "1. Brainstorming & Ideation",
        "items": [
            ("brainstorming-notes", "Brainstorming Notes"),
            ("problem-statement", "Problem Statement"),
        ],
    },
    {
        "id": "requirements",
        "title": "2. Requirement Analysis",
        "items": [
            ("data-dictionary", "Data Dictionary"),
            ("requirements-specification", "Requirements Specification"),
        ],
    },
    {
        "id": "design",
        "title": "3. Project Design Phase",
        "items": [
            ("pipeline-design", "Pipeline Design"),
            ("system-architecture", "System Architecture"),
        ],
    },
    {
        "id": "planning",
        "title": "4. Project Planning Phase",
        "items": [
            ("project-schedule", "Project Schedule"),
            ("risk-mitigation", "Risk Mitigation"),
        ],
    },
    {
        "id": "development",
        "title": "5. Project Development Phase",
        "items": [
            ("development-notes", "Development Notes"),
            ("model-selection", "Model Selection"),
        ],
    },
    {
        "id": "testing",
        "title": "6. Project Testing",
        "items": [
            ("code-testing", "Code Testing"),
            ("model-evaluation", "Model Evaluation"),
        ],
    },
    {
        "id": "documentation",
        "title": "7. Project Documentation",
        "items": [
            ("deployment-guide", "Deployment Guide"),
            ("user-guide", "User Guide"),
        ],
    },
    {
        "id": "demonstration",
        "title": "8. Project Demonstration",
        "items": [("demo-walkthrough", "Demo Walkthrough")],
    },
]

DOC_CONTENT = {
    "brainstorming-notes": {
        "title": "Brainstorming Notes",
        "sections": [
            (
                "Project Conception",
                "The team initiated OptiCrop to solve inconsistent crop selection decisions made without data. The primary idea was to combine soil nutrients and local weather into one ML-assisted recommendation workflow suitable for farmers, students, and agri teams.",
            ),
            (
                "User Personas",
                "Primary personas include field officers, small-scale farmers, and agri analysts. Their shared need is a fast recommendation system that explains why a crop is suggested and what season is suitable under current weather conditions.",
            ),
            (
                "Core Feature Wishlist",
                "High-priority features identified: location search, live weather fetch, upload-based soil extraction, strict input validation, Random Forest prediction, ranked crop list, season guidance, and a documentation portal for project traceability.",
            ),
            (
                "Feature Prioritization Outcome",
                "The final MVP scope prioritized reliability over visual complexity. The selected scope included prediction accuracy, transparent analysis bars, and clear explanation cards instead of advanced dashboards or user authentication in phase one.",
            ),
        ],
    },
    "problem-statement": {
        "title": "Problem Statement",
        "sections": [
            (
                "Current Agricultural Gap",
                "Many crop decisions are based on local habit instead of data-driven suitability. This causes low yields, avoidable input costs, and mismatch between crop choice and real-time climate conditions.",
            ),
            (
                "Operational Pain Points",
                "Manual interpretation of soil reports is time-consuming and error-prone. Existing tools often require technical setup, do not combine soil and weather effectively, or return generic outputs without confidence and season context.",
            ),
            (
                "Formal Problem Statement",
                "Design and implement a web application that accepts soil and weather inputs, validates data quality, and produces accurate crop recommendations with interpretable confidence and season fit, while remaining usable for non-technical users.",
            ),
            (
                "Success Criteria",
                "The solution is considered successful when users can complete end-to-end prediction quickly, receive distinct recommendations for distinct inputs, and understand the basis of recommendations through explainable analysis indicators.",
            ),
        ],
    },
    "data-dictionary": {
        "title": "Data Dictionary",
        "sections": [
            (
                "Model Input Fields",
                "N: Nitrogen (ppm), P: Phosphorous (ppm), K: Potassium (ppm), temperature: ambient air temperature (deg C), humidity: relative humidity (%), ph: soil pH value, rainfall: expected rainfall (mm).",
            ),
            (
                "Data Types and Ranges",
                "All inputs are numeric floats. Validation ranges in the predictor enforce practical bounds: N 0-140, P 0-145, K 0-205, temperature -10 to 55, humidity 0-100, pH 0-14, rainfall 0-500.",
            ),
            (
                "Derived Output Fields",
                "Predicted crop label, confidence score, ranked suitable crops, season fit, combined suitability score, parameter-wise status (Low/Optimal/High), and computed climate season are generated from validated inputs.",
            ),
            (
                "Source and Lineage Notes",
                "Structured files (CSV/JSON/TXT tables) are parsed directly; semi-structured reports use text pattern extraction; unsupported structures fallback to content fingerprint extraction to keep predictions deterministic per uploaded file.",
            ),
        ],
    },
    "requirements-specification": {
        "title": "Requirements Specification",
        "sections": [
            (
                "Functional Requirements",
                "The system shall support location search, weather retrieval, file upload parsing, input validation, Random Forest prediction, ranked output rendering, and documentation browsing for each project phase artifact.",
            ),
            (
                "Non-Functional Requirements",
                "Responses shall be delivered with low latency for interactive use. UI shall remain responsive on desktop and mobile, support light/dark theme consistency, and present prediction logic in clear human-readable language.",
            ),
            (
                "Validation Requirements",
                "The API shall reject missing or out-of-range values with descriptive messages. Upload parsing shall enforce allowed and blocked file types. Prediction endpoint shall return model-availability errors when pretrained artifacts are absent.",
            ),
            (
                "Compliance and Quality",
                "The system shall avoid destructive defaults, preserve deterministic behavior for repeated files, and provide explainable outputs suitable for academic demonstration and practical discussion with agricultural stakeholders.",
            ),
        ],
    },
    "pipeline-design": {
        "title": "Pipeline Design",
        "sections": [
            (
                "End-to-End Flow",
                "User selects location, application fetches live weather, user uploads soil report, backend extracts N/P/K/pH, UI validates readiness, prediction API computes ranked crops, and results page renders soil-climate analysis with season guidance.",
            ),
            (
                "Preprocessing Layer",
                "Input normalization converts values to numeric format and checks accepted bounds. Upload extraction supports structured and semi-structured reports while preserving deterministic fallback behavior for unsupported formats.",
            ),
            (
                "Inference Layer",
                "The Random Forest model receives seven aligned features in DataFrame format. Model output includes top prediction and class probabilities, which are transformed into ranked recommendations and combined with season-fit scoring.",
            ),
            (
                "Presentation Layer",
                "Frontend displays best crop, ranked alternatives, confidence bars, and explanatory metrics. This design emphasizes interpretability so users can compare options instead of relying on a single opaque recommendation.",
            ),
        ],
    },
    "system-architecture": {
        "title": "System Architecture",
        "sections": [
            (
                "Application Structure",
                "Flask provides routing and API orchestration; ML modules encapsulate predictor, weather integration, and soil upload parsing; Jinja templates handle server-rendered pages; static JS/CSS implement interactive workflow and themed UI.",
            ),
            (
                "Service Components",
                "Core modules: app.py (routes), ml/predictor.py (validation + inference), ml/location_weather.py (geolocation/weather), ml/soil_upload.py (file extraction), templates/documentation.html (portal rendering).",
            ),
            (
                "Data and Model Assets",
                "Pretrained model files are stored in models/random_forest.pkl with metrics in models/metrics.json. Runtime loads model lazily to reduce startup overhead and returns health metadata through /api/health.",
            ),
            (
                "Deployment Topology",
                "Single-container deployment with Gunicorn serves Flask app. Client browser communicates with REST endpoints; no external database required in current scope. Weather API is the primary external dependency for live climate values.",
            ),
        ],
    },
    "project-schedule": {
        "title": "Project Schedule",
        "sections": [
            (
                "Phase Breakdown",
                "Phase 1: ideation and problem framing. Phase 2: requirements and data schema finalization. Phase 3: model integration and workflow UI. Phase 4: testing, stabilization, and documentation portal completion.",
            ),
            (
                "Milestone Plan",
                "M1 - Baseline Flask app and pages; M2 - Prediction pipeline with trained model; M3 - File upload extraction and validation; M4 - Full results page with ranked crops; M5 - Documentation portal and final QA.",
            ),
            (
                "Dependency Sequencing",
                "Prediction UI depended on reliable API contracts; documentation pages depended on stable navigation routes; deployment configuration finalization depended on model artifact strategy and startup behavior validation.",
            ),
            (
                "Delivery Readiness",
                "Release readiness was defined by passing API checks, no critical template/runtime errors, deterministic recommendation behavior, and complete end-user flow from upload to interpretable recommendations.",
            ),
        ],
    },
    "risk-mitigation": {
        "title": "Risk Mitigation",
        "sections": [
            (
                "Model Availability Risk",
                "Risk: missing model files at runtime causes failed predictions. Mitigation: explicit model existence checks, health endpoint visibility, and clear error messages instructing artifact placement or retraining path.",
            ),
            (
                "Input Quality Risk",
                "Risk: incomplete or malformed uploads cause incorrect recommendations. Mitigation: strict validation ranges, structured parsing first strategy, text fallback extraction, and user-visible extraction summaries before submission.",
            ),
            (
                "Runtime Regression Risk",
                "Risk: template or route changes introduce runtime exceptions. Mitigation: centralized doc routing, lint checks after edits, conservative refactors, and endpoint-level guards for invalid slugs and missing inputs.",
            ),
            (
                "User Trust Risk",
                "Risk: users distrust a single output without explanation. Mitigation: ranked crop alternatives, confidence percentages, parameter analysis bars, and explicit season-fit indicators to improve transparency.",
            ),
        ],
    },
    "development-notes": {
        "title": "Development Notes",
        "sections": [
            (
                "Implementation Highlights",
                "The workflow was simplified into three user steps and one full results page. This reduced user friction and aligned data collection order with the model's required feature set.",
            ),
            (
                "Key Backend Changes",
                "Predictor now uses named DataFrame features, expanded seven-parameter analysis, season inference logic, and ranked recommendation output. Soil upload supports broader file types with deterministic extraction fallback.",
            ),
            (
                "Frontend Improvements",
                "Navigation received a Documentation entry beside theme toggle. Results rendering was enhanced to show climate season, combined crop score, per-parameter fit bars, and ranked suitable crops rather than repetitive outputs.",
            ),
            (
                "Stability Fix Notes",
                "Recent runtime bug in documentation template was caused by using group.items in Jinja on dict objects. Fix: switched to group['items'] access to iterate correctly over configured tuples.",
            ),
        ],
    },
    "model-selection": {
        "title": "Model Selection",
        "sections": [
            (
                "Candidate Consideration",
                "The project evaluated practical classifiers suitable for tabular agronomic features. Priority criteria included strong multiclass performance, robustness to mixed value distributions, and predictable inference behavior.",
            ),
            (
                "Chosen Model",
                "Random Forest classifier was selected due to high accuracy on available training distribution, low feature scaling requirements, stable generalization, and built-in probability output for ranked recommendations.",
            ),
            (
                "Selection Rationale",
                "Compared with single-tree or linear approaches, Random Forest better captured nonlinear interactions between nutrients and climate. It also reduced overfitting risk through ensemble averaging.",
            ),
            (
                "Operational Notes",
                "The deployed approach uses pretrained artifacts for predictable startup behavior. Model metadata is exposed through metrics.json and surfaced in UI to maintain auditability of model version and training profile.",
            ),
        ],
    },
    "code-testing": {
        "title": "Code Testing",
        "sections": [
            (
                "Route and API Testing",
                "Verified page routes load without template errors: home, workflow, about, and documentation details. API routes tested for weather, upload parsing, prediction, and health responses with valid and invalid payloads.",
            ),
            (
                "Validation Testing",
                "Boundary values and missing fields were tested to confirm descriptive 400 responses. Upload test matrix included CSV, JSON, text reports, image files, and blocked extension handling.",
            ),
            (
                "UI Flow Testing",
                "Wizard progression tested end-to-end: location selection, weather fetch, file upload analysis, validation checks, preprocessing step, and final ranked recommendation rendering with action buttons.",
            ),
            (
                "Regression Testing",
                "Documentation portal navigation, active link states, and dark mode styles were tested after route/template refactors. Lint diagnostics were checked for modified files after each substantial edit.",
            ),
        ],
    },
    "model-evaluation": {
        "title": "Model Evaluation",
        "sections": [
            (
                "Evaluation Summary",
                "Model performance is tracked through metrics.json, including test accuracy, sample counts, and class-wise report. The current Random Forest profile demonstrates high classification performance on the training distribution.",
            ),
            (
                "Practical Validation",
                "Beyond aggregate accuracy, practical validation focused on input sensitivity: different soil/weather combinations must produce distinct top recommendations and meaningful alternative crop rankings.",
            ),
            (
                "Explainability Signals",
                "Evaluation includes confidence distribution, parameter-level fit statuses, and season-fit augmentation. These signals are used to verify recommendation plausibility and improve user interpretation.",
            ),
            (
                "Limitations and Next Steps",
                "Current model quality depends on historical dataset coverage. Future evaluation should include field feedback loops, regional calibration, and periodic retraining with updated climate and soil sampling data.",
            ),
        ],
    },
    "deployment-guide": {
        "title": "Deployment Guide",
        "sections": [
            (
                "Prerequisites",
                "Install Python 3.10+ and project dependencies from requirements.txt. Ensure models/random_forest.pkl and models/metrics.json are available in deployment artifact.",
            ),
            (
                "Local Deployment",
                "Run application using python app.py for development. Verify /api/health returns model_loaded true, then validate end-to-end prediction flow through /workflow.",
            ),
            (
                "Production Deployment",
                "Use Gunicorn start command: gunicorn app:app --bind 0.0.0.0:$PORT. Configure environment with stable network access for weather API calls and monitor app logs for upload and prediction errors.",
            ),
            (
                "Post-Deployment Checklist",
                "Confirm navigation routes, documentation detail pages, upload API behavior, prediction API responses, theme toggle persistence, and overall latency under expected user load.",
            ),
        ],
    },
    "user-guide": {
        "title": "User Guide",
        "sections": [
            (
                "How to Run a Prediction",
                "Open Crop Predict, search and select location, wait for weather auto-fill, upload soil report file, complete validation, and submit to view ranked crop recommendations.",
            ),
            (
                "Understanding the Results",
                "Top recommendation indicates best match for provided inputs. Additional suitable crops show alternatives with confidence and season fit. Analysis bars explain how each parameter aligns with crop growth needs.",
            ),
            (
                "Upload Best Practices",
                "Prefer files containing clear N, P, K, and pH values. Structured CSV/JSON yields strongest extraction quality. For reports/images, verify extracted values displayed before moving to final prediction step.",
            ),
            (
                "Troubleshooting",
                "If prediction fails, confirm all inputs are present and within allowed range, ensure model files exist, and retry with a valid file format. Use /api/health to confirm model readiness status.",
            ),
        ],
    },
    "demo-walkthrough": {
        "title": "Demo Walkthrough",
        "sections": [
            (
                "Demo Narrative",
                "Introduce the agricultural decision challenge, show OptiCrop workflow, and explain how soil plus live weather produce transparent ML-backed crop recommendations.",
            ),
            (
                "Live Demo Sequence",
                "Step 1: choose location and fetch weather. Step 2: upload soil report and inspect extracted nutrients. Step 3: run prediction and review ranked crops, season guidance, and analysis bars.",
            ),
            (
                "Key Talking Points",
                "Highlight deterministic upload handling, strong model confidence, recommendation diversity by input variation, and formal project documentation traceability through the portal.",
            ),
            (
                "Q and A Preparation",
                "Keep fallback examples for alternate soil/weather combinations, explain model choice rationale, and present deployment readiness checklist to demonstrate practical applicability beyond prototype stage.",
            ),
        ],
    },
}

DOC_DIAGRAMS = {
    "brainstorming-notes": (
        "START\n"
        "  |\n"
        "  +--> Collect field pain points\n"
        "  +--> Map user personas and goals\n"
        "  +--> Group ideas by value and effort\n"
        "  +--> Prioritize MVP features\n"
        "  +--> Freeze phase-1 scope\n"
        "END"
    ),
    "problem-statement": (
        "Current crop decision issue\n"
        "        |\n"
        "        v\n"
        "No soil-weather combined analysis\n"
        "        |\n"
        "        v\n"
        "High risk crop choice + low yield confidence\n"
        "        |\n"
        "        v\n"
        "Need explainable ML recommendation workflow"
    ),
    "data-dictionary": (
        "Upload/Location Inputs\n"
        "   |--> N, P, K, pH\n"
        "   |--> Temperature, Humidity, Rainfall\n"
        "        |\n"
        "        v\n"
        "Validation + Type Normalization\n"
        "        |\n"
        "        v\n"
        "Feature Vector [7 fields] -> Model API Response"
    ),
    "requirements-specification": (
        "Business Objectives\n"
        "      |\n"
        "      +--> Functional requirements\n"
        "      +--> Non-functional requirements\n"
        "      +--> Validation and acceptance criteria\n"
        "      +--> Release readiness checklist"
    ),
    "pipeline-design": (
        "STEP 1  User selects location\n"
        "        -> Live weather fetched\n"
        "STEP 2  User uploads soil report\n"
        "        -> N/P/K/pH extracted\n"
        "STEP 3  Input validation checks\n"
        "STEP 4  Random Forest prediction\n"
        "STEP 5  Ranked crops + season fit + analysis"
    ),
    "system-architecture": (
        "Browser (UI Templates + JS)\n"
        "        |\n"
        "        v\n"
        "Flask Route Layer (app.py)\n"
        "        |\n"
        "        +--> ml/soil_upload.py\n"
        "        +--> ml/location_weather.py\n"
        "        +--> ml/predictor.py\n"
        "        |\n"
        "        v\n"
        "Model Artifacts (random_forest.pkl, metrics.json)"
    ),
    "project-schedule": (
        "Phase 1: Ideation and scope\n"
        "Phase 2: Requirements and architecture\n"
        "Phase 3: Development and integration\n"
        "Phase 4: Testing and stabilization\n"
        "Phase 5: Documentation and demonstration"
    ),
    "risk-mitigation": (
        "Risk Identified\n"
        "   |\n"
        "   +--> Severity scoring\n"
        "   +--> Owner assignment\n"
        "   +--> Mitigation action\n"
        "   +--> Weekly review\n"
        "   +--> Closure validation"
    ),
    "development-notes": (
        "Backlog -> Build -> Review -> Refine -> Release\n"
        "   |         |        |        |        |\n"
        " user      code     QA      polish    deploy\n"
        " story    commit   checks   update    ready"
    ),
    "model-selection": (
        "Candidate models shortlist\n"
        "        |\n"
        "        v\n"
        "Evaluate accuracy + stability + explainability\n"
        "        |\n"
        "        v\n"
        "Select Random Forest\n"
        "        |\n"
        "        v\n"
        "Deploy with probability-based ranking"
    ),
    "code-testing": (
        "Unit/API tests   UI flow tests\n"
        "      \\             /\n"
        "       \\           /\n"
        "        Regression Suite\n"
        "               |\n"
        "               v\n"
        "        Release confidence"
    ),
    "model-evaluation": (
        "Train/Test Metrics\n"
        "      +\n"
        "Input Variation Checks\n"
        "      +\n"
        "Explainability Review\n"
        "      |\n"
        "      v\n"
        "Model acceptance decision"
    ),
    "deployment-guide": (
        "Prepare artifacts\n"
        "      -> Configure runtime\n"
        "      -> Start gunicorn service\n"
        "      -> Validate /api/health\n"
        "      -> Run workflow smoke test\n"
        "      -> Go live"
    ),
    "user-guide": (
        "1) Search location and confirm weather\n"
        "2) Upload soil file and verify extracted values\n"
        "3) Submit prediction request\n"
        "4) Review top crop + alternatives\n"
        "5) Use season and analysis insights"
    ),
    "demo-walkthrough": (
        "Intro context\n"
        "   -> Live workflow execution\n"
        "   -> Explain recommendation output\n"
        "   -> Show architecture and quality checks\n"
        "   -> Take questions with evidence"
    ),
}

DOC_CODES = {
    "brainstorming-notes": "priority_score = impact * feasibility\nif priority_score >= 20:\n    include_in_mvp = True",
    "problem-statement": "problem = {\n  'decision_without_data': True,\n  'expected_outcome': 'reliable_crop_selection'\n}",
    "data-dictionary": "payload = {'N': 78, 'P': 42, 'K': 39, 'temperature': 27.1,\n           'humidity': 79.0, 'ph': 6.6, 'rainfall': 210}",
    "requirements-specification": "assert api_predict_status == 200\nassert 'suitable_crops' in response_json",
    "pipeline-design": "features_df = pd.DataFrame([[N,P,K,temp,hum,ph,rain]], columns=FEATURE_COLUMNS)\nproba = model.predict_proba(features_df)[0]",
    "system-architecture": "@app.route('/api/predict', methods=['POST'])\ndef api_predict():\n    return jsonify(predict(cleaned))",
    "project-schedule": "milestones = ['M1', 'M2', 'M3', 'M4', 'M5']\ncompleted = [m for m in milestones if status[m] == 'done']",
    "risk-mitigation": "if model_missing:\n    raise RuntimeError('model artifact unavailable')",
    "development-notes": "git add .\ngit commit -m 'enhance docs portal and prediction flow'",
    "model-selection": "rf = RandomForestClassifier(n_estimators=200, random_state=42)\nrf.fit(X_train, y_train)",
    "code-testing": "def test_predict_endpoint(client):\n    assert client.post('/api/predict', json=payload).status_code == 200",
    "model-evaluation": "accuracy = accuracy_score(y_test, y_pred)\nprint(f'Accuracy: {accuracy:.2%}')",
    "deployment-guide": "gunicorn app:app --bind 0.0.0.0:$PORT",
    "user-guide": "1) Select location\n2) Upload soil report\n3) Submit and compare ranked crops",
    "demo-walkthrough": "talk_track = ['Context', 'Live Demo', 'Insights', 'Questions']",
}

DOC_HIGHLIGHTS = {
    "brainstorming-notes": "The most important brainstorming output was moving from generic advice to evidence-backed crop ranking.",
    "problem-statement": "The critical issue is decision risk caused by missing soil-weather integration in day-to-day crop selection.",
    "data-dictionary": "Prediction quality depends directly on clean N/P/K/pH and weather values; validation is mandatory.",
    "requirements-specification": "Requirements were finalized with a strong emphasis on explainability, not only raw model accuracy.",
    "pipeline-design": "The pipeline ensures each prediction is input-driven; no static recommendation should appear across different datasets.",
    "system-architecture": "Modular ML services keep prediction, weather, and upload parsing independent for easier upgrades.",
    "project-schedule": "Milestones were sequenced to stabilize backend contracts before UI detail expansion.",
    "risk-mitigation": "Input-quality and artifact-availability risks were treated as top-priority blockers.",
    "development-notes": "The project shifted from multi-step fragmented results to a single consolidated recommendation experience.",
    "model-selection": "Random Forest was selected for strong multiclass performance and probability-based ranking support.",
    "code-testing": "Regression checks specifically target route/template failures and prediction endpoint correctness.",
    "model-evaluation": "Practical evaluation includes recommendation diversity across different input combinations.",
    "deployment-guide": "Always validate /api/health before demo or production validation runs.",
    "user-guide": "Users should verify extracted nutrient values before final submission to improve recommendation quality.",
    "demo-walkthrough": "A strong demo combines technical depth with clear agricultural decision impact.",
}

DOC_EXEC_CONTEXT = {
    "brainstorming-notes": "This page captures the strategic ideation record used to justify feature selection and MVP scoping decisions.",
    "problem-statement": "This page defines the business and agricultural problem in measurable terms to align engineering and impact goals.",
    "data-dictionary": "This page formalizes data definitions and contracts to ensure consistency across extraction, validation, and inference.",
    "requirements-specification": "This page documents what the product must do, how well it must perform, and how completion is verified.",
    "pipeline-design": "This page describes the complete technical flow from raw input collection to explainable recommendation output.",
    "system-architecture": "This page explains the software architecture layers, interfaces, and operational responsibilities.",
    "project-schedule": "This page presents delivery sequencing, milestone governance, and release readiness checkpoints.",
    "risk-mitigation": "This page outlines critical risk controls and accountability measures used to preserve delivery quality.",
    "development-notes": "This page records implementation decisions, refactors, and stabilization outcomes during development.",
    "model-selection": "This page documents model choice rationale, evaluation basis, and production suitability reasoning.",
    "code-testing": "This page summarizes software test coverage strategy and execution outcomes supporting release confidence.",
    "model-evaluation": "This page consolidates model quality evidence across metrics, behavior, and interpretability checks.",
    "deployment-guide": "This page provides operationally safe deployment instructions and verification standards.",
    "user-guide": "This page provides structured user instructions for accurate and repeatable prediction usage.",
    "demo-walkthrough": "This page provides a professional demonstration script for technical and non-technical audiences.",
}


def _build_doc_sections(doc_slug: str, base_sections: list[tuple[str, str]]) -> list[dict]:
    sections = []
    for idx, (title, body) in enumerate(base_sections):
        sections.append(
            {
                "title": title,
                "body": body,
                "highlight": DOC_HIGHLIGHTS.get(doc_slug) if idx == 0 else "",
                "points": [
                    "Defines the section objective, assumptions, and decision boundaries in formal language.",
                    "Maps each observation to practical project outcomes and implementation relevance.",
                    "Maintains alignment with current OptiCrop architecture, model flow, and UI behavior.",
                    "Supports academic report writing, technical review, and viva presentation usage.",
                ]
                if idx in (0, 1)
                else [
                    "Includes implementation-level detail with concise, audit-friendly bullet points.",
                    "Connects design decisions to measurable quality and delivery outcomes.",
                    "Provides clear guidance for future enhancement and maintenance planning.",
                ],
                "diagram": DOC_DIAGRAMS.get(doc_slug, "") if idx in (1, 2) else "",
                "code": DOC_CODES.get(doc_slug, "") if idx == 3 else "",
            }
        )

    sections.append(
        {
            "title": "Executive Context and Professional Notes",
            "body": DOC_EXEC_CONTEXT.get(
                doc_slug,
                "This section provides executive-level context and professional framing for stakeholders.",
            ),
            "highlight": "This section is prepared in formal report style to support reviews, submissions, and demonstrations.",
            "points": [
                "Language quality is kept professional, direct, and presentation-ready.",
                "The documented content is structured for quick scanning and detailed reading.",
                "Decision rationale is preserved for governance and future audits.",
            ],
            "diagram": DOC_DIAGRAMS.get(doc_slug, ""),
            "code": "",
        }
    )

    sections.append(
        {
            "title": "Architecture and Flowchart Summary",
            "body": (
                "The following flowchart summarizes how this page connects to the overall OptiCrop delivery model, "
                "including data flow, validation controls, and output governance."
            ),
            "highlight": "Use this flowchart during project review meetings and final presentations for clear stakeholder communication.",
            "points": [
                "Input quality controls are enforced before prediction or reporting decisions.",
                "Every stage contains traceable checkpoints to improve reliability.",
                "Outputs are intentionally explainable to maintain user trust and adoption.",
            ],
            "diagram": DOC_DIAGRAMS.get(doc_slug, ""),
            "code": DOC_CODES.get(doc_slug, ""),
        }
    )
    return sections


def create_app() -> Flask:
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "opticrop-dev-key-change-in-production"

    @app.context_processor
    def inject_globals():
        metrics = get_metrics() if MODEL_PATH.exists() else {}
        return {
            "model_metrics": metrics,
            "model_ready": MODEL_PATH.exists(),
        }

    @app.route("/")
    def index():
        return render_template("index.html")

    @app.route("/workflow")
    def workflow():
        return render_template("workflow.html")

    @app.route("/prediction")
    def prediction():
        return redirect(url_for("workflow"))

    @app.route("/api/locations/search")
    def api_locations_search():
        query = request.args.get("q", "").strip()
        if len(query) < 2:
            return jsonify([])
        try:
            return jsonify(search_locations(query))
        except Exception:
            return jsonify([])

    @app.route("/api/weather/live", methods=["POST"])
    def api_weather_live():
        data = request.get_json(silent=True) or {}
        lat = data.get("lat")
        lon = data.get("lon")
        if lat is None or lon is None:
            return jsonify({"error": "Location coordinates required."}), 400
        try:
            weather = fetch_live_weather(float(lat), float(lon))
            weather["location"] = data.get("label", "")
            return jsonify(weather)
        except Exception:
            return jsonify({"error": "Could not fetch live weather for this location."}), 502

    @app.route("/api/weather", methods=["POST"])
    def api_weather():
        """Legacy demo endpoint — prefer /api/weather/live."""
        data = request.get_json(silent=True) or {}
        lat, lon = data.get("lat"), data.get("lon")
        if lat is not None and lon is not None:
            try:
                return jsonify(fetch_live_weather(float(lat), float(lon)))
            except Exception:
                pass
        state = (data.get("state") or "Default").lower()
        # Demo weather profiles by region name hash
        profiles = {
            "karnataka": {"temperature": 26.5, "humidity": 78, "rainfall": 210},
            "maharashtra": {"temperature": 28.0, "humidity": 72, "rainfall": 185},
            "punjab": {"temperature": 22.0, "humidity": 65, "rainfall": 120},
            "kerala": {"temperature": 29.0, "humidity": 85, "rainfall": 280},
            "tamil nadu": {"temperature": 30.5, "humidity": 70, "rainfall": 195},
        }
        profile = profiles.get(state, {"temperature": 25.0, "humidity": 80, "rainfall": 200})
        return jsonify({"source": "Weather API (demo)", **profile})

    @app.route("/api/upload-soil", methods=["POST"])
    def api_upload_soil():
        if "file" not in request.files:
            return jsonify({"error": "No file uploaded."}), 400

        upload = request.files["file"]
        if not upload.filename:
            return jsonify({"error": "No file selected."}), 400

        try:
            data = parse_upload(upload.filename, upload.read())
            return jsonify(data)
        except ValueError as exc:
            return jsonify({"error": str(exc)}), 400
        except Exception:
            return jsonify({"error": "Could not read the uploaded file."}), 400

    @app.route("/prediction/form", methods=["GET", "POST"])
    def prediction_form():
        result = None
        error = None
        form_data = {}

        if request.method == "POST":
            form_data = {
                "N": request.form.get("N", ""),
                "P": request.form.get("P", ""),
                "K": request.form.get("K", ""),
                "temperature": request.form.get("temperature", ""),
                "humidity": request.form.get("humidity", ""),
                "ph": request.form.get("ph", ""),
                "rainfall": request.form.get("rainfall", ""),
            }

            if not MODEL_PATH.exists():
                error = "ML model not found. Ensure models/random_forest.pkl is present."
            else:
                cleaned, validation_error = validate_inputs(form_data)
                if validation_error:
                    error = validation_error
                else:
                    result = predict(cleaned)

        return render_template(
            "prediction.html",
            result=result,
            error=error,
            form_data=form_data,
        )

    @app.route("/about")
    def about():
        return render_template("about.html")

    @app.route("/documentation")
    def documentation():
        default_slug = DOC_GROUPS[0]["items"][0][0]
        return redirect(url_for("documentation_detail", doc_slug=default_slug))

    @app.route("/documentation/<doc_slug>")
    def documentation_detail(doc_slug: str):
        if doc_slug not in DOC_CONTENT:
            return redirect(url_for("documentation"))

        current_doc = DOC_CONTENT[doc_slug]
        current_group = next(
            (group for group in DOC_GROUPS if any(slug == doc_slug for slug, _ in group["items"])),
            DOC_GROUPS[0],
        )
        current_sections = _build_doc_sections(doc_slug, current_doc["sections"])
        return render_template(
            "documentation.html",
            doc_groups=DOC_GROUPS,
            current_slug=doc_slug,
            current_doc=current_doc,
            current_group=current_group,
            current_sections=current_sections,
        )

    @app.route("/api/predict", methods=["POST"])
    def api_predict():
        if not MODEL_PATH.exists():
            return jsonify({"error": "ML model not found. Ensure models/random_forest.pkl is present."}), 503

        data = request.get_json(silent=True) or {}
        cleaned, validation_error = validate_inputs(data)
        if validation_error:
            return jsonify({"error": validation_error}), 400

        return jsonify(predict(cleaned))

    @app.route("/api/predict/pdf", methods=["POST"])
    def api_predict_pdf():
        result = request.get_json(silent=True) or {}
        if not result or "crop" not in result:
            return jsonify({"error": "Prediction result payload is required."}), 400

        try:
            pdf_bytes = _build_prediction_pdf(result)
        except RuntimeError as exc:
            return jsonify({"error": str(exc)}), 503

        return send_file(
            io.BytesIO(pdf_bytes),
            mimetype="application/pdf",
            as_attachment=True,
            download_name="Crop_recommendations.pdf",
        )

    @app.route("/api/health")
    def health():
        metrics = get_metrics() if MODEL_PATH.exists() else {}
        return jsonify(
            {
                "status": "ok" if MODEL_PATH.exists() else "model_missing",
                "model_loaded": MODEL_PATH.exists(),
                "accuracy": metrics.get("accuracy"),
                "crops": metrics.get("num_crops"),
            }
        )

    return app


app = create_app()

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
